FROM node:18-alpine As base
WORKDIR /usr/src/app
# Copying this first prevents re-running npm install on every code change.
COPY --chown=node:node package*.json ./
RUN npm ci
COPY --chown=node:node . .
USER node

# BUILD
FROM node:18-alpine
WORKDIR /usr/src/app
# COPY node_modules from previous stage to build
COPY --chown=node:node --from=base /usr/src/app/node_modules ./node_modules
RUN npm run build
COPY --chown=node:node /usr/src/app/dist ./dist
COPY --chown=node:node /usr/src/app/.env.development .env
USER node

EXPOSE 4000
CMD [ "node", "dist/app.js" ]

